#!/bin/bash

git clone https://github.com/zaradev/android_device_htc_zara-common.git -b cm-12.0
git clone https://github.com/zaradev/android_kernel_htc_msm8960.git -b cm-12.0
git clone https://github.com/zaradev/android_device_htc_zara.git -b cm-12.0
git clone https://github.com/zaradev/android_device_htc_msm8960-common.git -b cm-12.0
